baldinof_road_runner:
    # When the kernel should be rebooted.
    # See https://github.com/baldinof/roadrunner-bundle#kernel-reboots
    kernel_reboot:
        # if you want to use a fresh container on each request, use the `always` strategy
        strategy: on_exception
        # Exceptions you KNOW that do not put your app in an errored state
        allowed_exceptions:
            - App/Exception/ApplicationException

    metrics:
        enabled: false
