version: "3"

networks:
  ticket-service-network:

services:
  ticket-service-app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: ticket-app
    ports:
      - "8085:8080"
    depends_on:
      - ticket-service-db
    volumes:
      - .:/var/www/ticket-service
      - .docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - ticket-service-network

  ticket-service-db:
    image: mariadb:10.9.3
    container_name: ticket-db
    ports:
      - "6306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-qwerty}
      MYSQL_PASSWORD: ${DB_PASSWORD:-qwerty}
      MYSQL_USER: ${DB_USER:-ticket-service}
      MYSQL_DATABASE: ${DB_DATABASE:-ticket-service}
    networks:
      - ticket-service-network
